project:
  type: website

website:
  description: "Youssef Kharchouf's personal notes"
  site-url: https://nightowl97.github.io/personal_blog/ # you must change this appropriately for RSS feeds to work properly
  title: "Youssef Kharchouf"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nightowl97
      - icon: linkedin
        href: https://www.linkedin.com/in/youssefkhar/
      - icon: bi-mortarboard-fill
        href: https://scholar.google.com/citations?user=rjjVxSYAAAAJ
format:
  html:
    theme:
      - flatly 
      - customtheme.scss
    css: styles.css
    fontsize: 1.2em
    # template-partials:
    #   - title-block.html

  # pdf:
  #     include-in-header:
  #       text: |
  #         \usepackage{xcolor}
  #         \pagecolor[HTML]{1E1E1E}
  #         \color[HTML]{F5F5F5}
